### ISSUE TITLE
Tcl_NREvalObj Error

### ISSUE THREAD

**Issue by verbomania** [RubyLane/rl_json#23]
Hi

Is there a minimum requirement of TCL8.6 for rl_json? I'm testing it in TCL8.5 and when I issue `package require rl_json`, I'm getting `/lib/rl_json0.9.11/librl_json0.9.11.so: undefined symbol: Tcl_NREvalObj`

Thanks

Steve

**Comment by cyanogilvie** [comment]
Yes, rl_json requires 8.6 - it uses the Non-Recursive Engine: http://wiki.tcl.tk/37253 which is only in 8.6.

With enough effort it might be possible to get it working on 8.5, but I don't have any reason to do it - I've been using 8.6 for almost a decade now.  If you wanted to have a go at it, you'd be best off starting from e844a95d^ (just before the NRE conversion).  It wouldn't be able to be merged back upstream, but you could maintain an 8.5-compatible fork if you wanted to.

**Comment by verbomania** [comment]
Thanks for getting back to me. The reasons for being stuck on 8.5 on this particular server are long and complicated and involve some substantial legacy code. I'm actually using the pre-8.6, version 0.9.7 which works absolutely fine for this purpose.
