### ISSUE TITLE
How to install the rl_json

### ISSUE THREAD

**Issue by siyueyinghua** [RubyLane/rl_json#30]
How to install this module? which is not described in README file?

**Comment by cyanogilvie** [comment]
It is just the standard TEA pattern followed by all Tcl extensions:
configure; make; make install

**Comment by siyueyinghua** [comment]
Thanks very much! 
I use command sequence as you said: configure; make; make install
but when i use, it give the error "can't find package rl_json"

```
% package require rl_json
can't find package rl_json
```
in addition, i run the command "make test", it turns out all test passed, as flowing:

```

LD_LIBRARY_PATH=".:/usr/lib:/home/yesire-lincoln/Downloads/vulkansdk_1.2.135.0/x86_64/lib:" PATH=".:/usr/lib:/home/yesire-lincoln/.conda/envs/pDL/bin:/usr/bin/miniconda3/condabin:/home/yesire-lincoln/Downloads/vulkansdk_1.2.135.0/x86_64/bin:/home/yesire-lincoln/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/yesire-lincoln/ProgramHub/Vulkan-Samples/build/linux/app/bin/Release/x86_64:/usr/local/cuda-11.1/bin" TCLLIBPATH="." TCL_LIBRARY=`echo /usr/include/tcl8.6/tcl-private/library` /usr/bin/tclsh8.6 `echo ./tests/all.tcl`  \
	-load "package ifneeded rl_json 0.11.0 \
		[list load `echo librl_json0.11.0.so` rl_json]"
Tests running in interp:       /usr/bin/tclsh8.6
Tests running with pwd:        /home/yesire-lincoln/ProgramHub/programLanguageLearn/thirdParty/rl_json
Tests running in working dir:  /home/yesire-lincoln/ProgramHub/programLanguageLearn/thirdParty/rl_json/tests
Only running tests that match:        *
Skipping test files that match:       l.*.test
Only sourcing test files that match:  *.test
Tests began at Mon Jan 04 22:36:04 CST 2021
_parser.test
amap.test
array.test
boolean.test
decode.test
exists.test
extract.test
foreach.test
get.test
jsontestsuite.test
keys.test
length.test
lmap.test
memory.test
misc.test
new.test
normalize.test
number.test
object.test
omap.test
parse.test
pretty.test
can't find package parse_args
set.test
can't find package parse_args
string.test
template.test
template_string.test
type.test
unset.test
can't find package parse_args
valid.test

Tests ended at Mon Jan 04 22:36:05 CST 2021
all.tcl:	Total	2346	Passed	2346	Skipped	0	Failed	0
Sourced 0 Test Files.

```

please help me figure out what's wrong?

**Comment by cyanogilvie** [comment]
Take a look where 'make install' installs the package, and make sure that's
in your Tcl $::auto_path list - the standard Tcl things for packages,
rl_json does nothing complicated or out of the ordinary.

**Comment by gl-yziquel** [comment]
> I also was looking for installation instructions. If you're new to TCL, "It is just the standard TEA pattern followed by all Tcl extensions" is not that useful. So if anyone else comes looking here for instructions this is the Docker layer I ended up using:

Absolutely. Spent a few hours trying to figure out where the tclconfig/tcl.m4 macro came from. Detailed installation instructions allow to avoid that kind of confusion: that tcl.m4 is pulled from the git submodule command (as the tclconfig/m4 provided in debian is not picked up by `autoreconf -vif`.)
