### ISSUE TITLE
Wrong dispatch for unistd.h in generic/rl_jsonInt.h

### ISSUE THREAD

**Issue by wkechel** [RubyLane/rl_json#33]
The correct disp[atch for the presence of unistd.h is:

  #include <math.h>
  #include <stddef.h>
  #include <stdint.h>
+ #if defined(HAVE_UNISTD_H)
  #include <unistd.h>
+ #endif
  #include <tclTomMath.h>
  #include "tip445.h"

**Comment by cyanogilvie** [comment]
Thanks, I've incorporated the change
