### ISSUE TITLE
rl_json 0.11.1 fails to link under Windows 10 with cl when cmpiled in 32 bit mode

### ISSUE THREAD

**Issue by wkechel** [RubyLane/rl_json#37]
Here is a trace of the log:

cl -DPACKAGE_NAME=\"rl_json\" -DPACKAGE_TARNAME=\"rl_json\" -DPACKAGE_VERSION=\"0.11.1\" -DPACKAGE_STRING=\"rl_json\ 0.11.1\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DBUILD_rl_json=/\*\*/
 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DENSEMBLE=0 -DDEDUP=1 -DTCL_THREADS=1 -D
USE_TCL_STUBS=1 -DUSE_TCLOO_STUBS=1 -DMODULE_SCOPE=extern -DHAVE_STDBOOL_H=1 -DTIP445_SHIM=1  -I"P:/g480/gbuild/rel/wintel/include"    -nologo -O2 -W2 -MD -DNDEBUG    -c `cygpath -m /p/g480/sr
c/rl_json-0.11.1/generic/rl_json.c` -o rl_json.obj
cl : Command line warning D9035 : option 'o' has been deprecated and will be removed in a future release
rl_json.c
cl -DPACKAGE_NAME=\"rl_json\" -DPACKAGE_TARNAME=\"rl_json\" -DPACKAGE_VERSION=\"0.11.1\" -DPACKAGE_STRING=\"rl_json\ 0.11.1\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DBUILD_rl_json=/\*\*/
 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DENSEMBLE=0 -DDEDUP=1 -DTCL_THREADS=1 -D
USE_TCL_STUBS=1 -DUSE_TCLOO_STUBS=1 -DMODULE_SCOPE=extern -DHAVE_STDBOOL_H=1 -DTIP445_SHIM=1  -I"P:/g480/gbuild/rel/wintel/include"    -nologo -O2 -W2 -MD -DNDEBUG    -c `cygpath -m /p/g480/sr
c/rl_json-0.11.1/generic/dedup.c` -o dedup.obj
cl : Command line warning D9035 : option 'o' has been deprecated and will be removed in a future release
dedup.c
rm -f rl_json0111.dll
link -dll  -nodefaultlib:libucrt.lib -nologo ucrt.lib  "P:/g480/gbuild/rel/wintel/lib/tclstub86.lib" -release -out:rl_json0111.dll parser.obj rl_json.obj json_types.obj dedup.obj api.obj rl_js
onStubInit.obj names.obj ; if test -f rl_json0111.dll.manifest ; then mt.exe -nologo -manifest rl_json0111.dll.manifest -outputresource:rl_json0111.dll\;2 ; fi
   Creating library rl_json0111.lib and object rl_json0111.exp
rl_json.obj : error LNK2019: unresolved external symbol _mkstemp referenced in function _checkmem
dedup.obj : error LNK2019: unresolved external symbol _ffs referenced in function _first_free
rl_json0111.dll : fatal error LNK1120: 2 unresolved externals
: rl_json0111.dll

**Comment by wkechel** [comment]
OK, here comes a full patch for the problems
[rl_json-0.11.1-diff.txt](https://github.com/RubyLane/rl_json/files/7595607/rl_json-0.11.1-diff.txt)

**Comment by cyanogilvie** [comment]
Thanks for these changes, I've incorporated as many as I can into the upcoming release.  Unfortunately, as a policy, I don't ever use mktemp in any code I maintain, for security reasons.  Also, the memory tests are too delicate to survive usefully to other platforms, so I've just made them all constrained on having a readable /proc/self/statm (linux only essentially).  The code is all common between the platforms so I don't expect platform-specific leaks, so just being able to check for them on linux should be ok (I also check using valgrind and much more extensive testing anyway).

I don't know what to make of cl deprecating -o, I don't see how else to have it build an object.  Also, that is part of the standard TEA build machinery, not maintained in this project but the tclconfig and sampleextension repos.

Sorry that it has taken so long to get to this, the last year has been a bit hectic.  In future, if you could submit patches with a pull request that would be best.
