### ISSUE TITLE
json exists - empty values - validation

### ISSUE THREAD

**Issue by bradennapier** [RubyLane/rl_json#6]
I am hoping I am not missing the obvious things here, loving this package!  Just a few things so far that I have run into, I may have missed certain details that would be used to handle such things.

There is no way to validate a value may or may not be json that I have found without using a try/catch type option.  For example:

```
set value {}
json exists $value key
```

This produces an error so there is really no way for me to run a command to properly handle the situation that I may not receive the json I am expecting, may have an empty value, or may unknowingly have a value that is not json (or perhaps already parsed from json).  I know the json package does have a validate but IIRC there was a couple weaknesses of that and it was not a very efficient validator (I could be completely off-base with this). 

If I am wrong with this then I will just start validating before every command - but I would still say mixing in the validation would make more sense in most cases.

Summary: Would like to see a `json validate $value` or `json isjson $value` and/or have `json exists $json_value key` return false in the case a value is not valid json.

Anyway, thank you for this package!  It has really helped make a lot of our code much cleaner.

**Comment by bradennapier** [comment]
If validate is the proper method than I would also point out:

```
% ::json::validate {}
1
```

vs

```
% json get {} key
Error parsing JSON value: No JSON value found at offset 0
```

so the validation will pass that it is valid then we will get an error, so we need to validate, then check for empty value, then get every single time we use this in the current setup.

**Comment by bradennapier** [comment]
FYI: http://wiki.tcl.tk/48276

**Comment by cyanogilvie** [comment]
I think a [json validate $value] could be provided, but there is an ambiguity to be resolved first - this package accepts a slightly expanded JSON syntax thta includes // and /* */ style comments, so if [json validate] considers anything that it can successfully operate on to be valid then it will return true for some values that aren't strictly valid JSON according to the spec.  If it takes the other approach and applies strict validation that will interfere with use cases like yours.  I would be inclined to say: just use it, assuming it's valid, and handle the exceptions with a try like so:

try {
    json get $value foo
    ....
} trap {RL JSON PARSE} {errmsg options} {
    # JSON wasn't valid
}

I checked how dict handled invalid values and the exists method, and it allows them and returns false for any key:

dict exists {foo bar baz} x

so there is a strong argument to be made for aligning rl_json to match that behaviour.

I'm not familiar with the details of ::json::validate, but it is definitely incorrect for it to return true for an empty string.

**Comment by bradennapier** [comment]
Empty string should return 0 but {{}} is definitely valid JSON

**Comment by cyanogilvie** [comment]
I've pushed a change to have [json exists $invalid foo] return false instead of throwing an error.  [json validate] will take a bit more thought

**Comment by bradennapier** [comment]
Awesome.  So the package is handling json5 or w/e it is for the syntax?

**Comment by bradennapier** [comment]
I added validate and a bunch more in the rl_json extensions i posted so that should work for now anyway.  Feel free to implement any of those things in C ;-) -- would be awesome to get a speed bump on such things.  

Anyway, thanks for the extension, it really is making a lot of things work better in our platform as I moved over to it (while also making me pull my hair out with the little bugs i am creating heh)

**Comment by cyanogilvie** [comment]
The only aspect that matches the syntax extensions of json5 is the comments.  I quite like the single correct representation property of json that allows normalised documents to compared using string equality, which is lost if the formatting rules are relaxed as json5 does.

I allowed comments in-line to improve the readability of large templates in particular.  [json normalize] and [json template] strip comments (with all other optional whitespace), so the result strictly conforms to the json standard.

If this command is accepted into the core (TIP pending), then it will be available to extend from a C extension (although the intrep is not the nicest to work with).  If it isn't I'll probably add stubs support so that other extensions can use it from C and they can for dicts

**Comment by bradennapier** [comment]
That makes sense.  I think this can be closed then.  Thanks for looking into all this and making those improvements.
