### ISSUE TITLE
Start using tags for versions / releases

### ISSUE THREAD

**Issue by bradennapier** [RubyLane/rl_json#7]
rkeene touched on this in a previous post requesting that you do something like this.  It isn't a huge deal but I added rl_json to the kitcreator (https://kitcreator.rkeene.org/fossil/home) build system which downloads the source and compiles it into a tcl distribution.  Right now with how it is setup we have to point to a specific commit

https://github.com/RubyLane/rl_json/archive/f4ad2a2755bedc9deb36cef245d85f593dc4c655.tar.gz

--  When using releases we can point to those instead.  I believe that if you were to add the tag to each version change then we can do

https://github.com/RubyLane/rl_json/archive/0.9.6.tar.gz

(Although I am not positive on that since I dont often use github).  

I know that can be done with branches.  When I do tags I run:

`git tag -a $::version -m "Version $::version build $::build"`

and by the way here is the kitcreator script to build rl_json into the tclkit:

```
#! /usr/bin/env bash

# BuildCompatible: KitCreator

version='0.9.5'
url="https://github.com/RubyLane/rl_json/archive/f4ad2a2755bedc9deb36cef245d85f593dc4c655.tar.gz"
sha256='0c5625437edf5863724e190be1984d3e51e91c84d32c00a12c89da4436b772fd'
internalpkgname='rl_json'
tclpkg='rl_json'
tclpkgversion='0.9.5'
```

**Comment by cyanogilvie** [comment]
I've added git tags for the versions as suggested, thanks.  The version link example works now
